
export const API_URL = "https://script.google.com/macros/s/AKfycbzPqSGs_bvnQPlNK1Efi196Uq2xyHIGUbmWdUjUMbx7sPRgSzGKnqnXlW0cVgjHXv_vKQ/exec";

export const translations = {
    vi: {
        loadingData: "Đang tải dữ liệu...",
        projectTitle: "Sản xuất cà phê sinh thái và Cải thiện rừng tự nhiên tại huyện Hướng Hoá",
        refreshButton: "Làm mới", resetButton: "Thiết lập lại", exportExcelBtn: "Xuất Báo Cáo", printButton: "In Trang", exitButton: "Thoát",
        totalFarmersLabel: "Tổng số hộ", totalPlotsLabel: "Tổng số lô", totalVillagesLabel: "Tổng số thôn", totalAreaLabel: "Tổng DT (ha)",
        totalPlantedTreesLabel: "Cây HT đã trồng", totalSpeciesLabel: "Tổng số loài", 
        totalSoilTestsLabel: "Hoàn thành điều tra",
        filterTitle: "Bộ lọc dữ liệu", yearLabel: "Năm", villageLabel: "Thôn", farmerLabel: "Nông dân", allOption: "Tất cả",
        supportLabel: "Hỗ trợ bởi", speciesLabel: "Loài cây", projectLabel: "Dự án",
        projectOptionSlow: "SLOW", projectOptionWwf: "PFFP/WWF",
        farmersTableTitle: "Thông tin hộ dân", plotsTableTitle: "Thông tin lô rừng chi tiết", yearlyTableTitle: "Dữ liệu sản xuất hàng năm",
        speciesTableTitle: "Thông tin các loài cây",
        trainingModalTitle: "Lịch sử tập huấn của",
        noTrainingData: "Không có dữ liệu tập huấn.",
        modalCloseButton: "Đóng",
        speciesTreeChartTitle: "Cây trồng theo loài (Năm)",
        th_TT: "TT", th_Actions: "Chi tiết", th_Farmer_ID: "ID Nông dân", th_Full_Name: "Họ tên", th_Gender: "Giới tính", th_Ethnicity: "Dân tộc", th_Village_Name: "Thôn",
        'th_Area (ha)': "Diện tích (ha)", th_Plot_Id: "ID Lô", th_Plot_Name: "Tên lô",
        th_Year: "Năm", th_Annual_Volume_Cherry: "Sản lượng cà phê tươi", th_Number_Shade_Trees_Planted: "Số cây đã trồng", 
        th_Shade_Trees_Species: "Loài cây che bóng", th_Shade_Trees_Died: "Số cây chết", 'th_Soil_Test_Support': "Hỗ trợ đất", 
        th_Species_ID: "Mã Loài", th_Species_Name: "Tên Loài", th_Species_Images: "Hình Ảnh", th_Species_Type: "Phân Loại",
        areaByVillageChartTitle: "Tổng diện tích theo thôn", ethnicityRatioChartTitle: "Tỷ lệ thành phần dân tộc",
    },
    en: {
        loadingData: "Loading data...",
        projectTitle: "Prosperous Farmers and Forests Partnership",
        refreshButton: "Refresh", resetButton: "Reset", exportExcelBtn: "Export Report", printButton: "Print Page", exitButton: "Exit",
        totalFarmersLabel: "Total Households", totalPlotsLabel: "Total Plots", totalVillagesLabel: "Total Villages", totalAreaLabel: "Total Area (ha)",
        totalPlantedTreesLabel: "Supported Trees Planted", totalSpeciesLabel: "Total Species", 
        totalSoilTestsLabel: "Survey Completed",
        filterTitle: "Data Filters", yearLabel: "Year", villageLabel: "Village", farmerLabel: "Farmer", allOption: "All",
        supportLabel: "Supported by", speciesLabel: "Species", projectLabel: "Project",
        projectOptionSlow: "SLOW", projectOptionWwf: "PFFP/WWF",
        farmersTableTitle: "Household Information", plotsTableTitle: "Detailed Plot Information", yearlyTableTitle: "Yearly Production Data",
        speciesTableTitle: "Species Information",
        trainingModalTitle: "Training History for",
        noTrainingData: "No training data available.",
        modalCloseButton: "Close",
        speciesTreeChartTitle: "Planted Trees by Species (Yearly)",
        th_TT: "No.", th_Actions: "Details", th_Farmer_ID: "Farmer ID", th_Full_Name: "Full Name", th_Gender: "Gender", th_Ethnicity: "Ethnicity", th_Village_Name: "Village",
        'th_Area (ha)': "Area (ha)", th_Plot_Id: "Plot ID", th_Plot_Name: "Plot Name",
        th_Year: "Year", th_Annual_Volume_Cherry: "Cherry Volume", th_Number_Shade_Trees_Planted: "Num Trees Planted", 
        th_Shade_Trees_Species: "Shade Tree Species", th_Shade_Trees_Died: "Num Trees Died", 'th_Soil_Test_Support': "Soil Test Support", 
        th_Species_ID: "Species ID", th_Species_Name: "Species Name", th_Species_Images: "Images", th_Species_Type: "Type",
        areaByVillageChartTitle: "Total Area by Village", ethnicityRatioChartTitle: "Ethnicity Ratio",
    }
};
